### ISSUE TITLE
SMS code not not filling automatically 

### ISSUE THREAD

**Issue by pstuashiqcse** [fbsamples/account-kit-samples-for-android#1]
All functionality working perfectly except automatic sms code filling.

I have added those to my mainfest and AccountKitConfiguration respectively 

```

 <uses-permission android:name="android.permission.READ_SMS" />
 <uses-permission android:name="android.permission.RECEIVE_SMS" />
```

```
configurationBuilder.setReadPhoneStateEnabled(true);
configurationBuilder.setReceiveSMS(true);
```

Interesting thing is, after integrating those configuration auto SMS worked perfectly, but after few SMS that again stopped working. What can I do?

**Comment by olgaikuznetsova** [comment]
What Android version are you using? For M+ you'll need to also request the permission via code (requestPermissions(new String[]{ permission }, requestCode);).

An example is here: http://stackoverflow.com/questions/33078003/android-6-0-permission-error

Please file any issues you have with Account Kit integration via the Facebook developer portal: https://developers.facebook.com/bugs/?tag_ids=1679169675664406

**Comment by pstuashiqcse** [comment]
Great! working like charm!

Thanks a lot...

**Comment by ducpt2** [comment]
@pstuashiqcse can you guild me to do this feature? Thanks.
