### ISSUE TITLE
Sending code

### ISSUE THREAD

**Issue by HaDiSs277** [fbsamples/account-kit-samples-for-android#2]
Hi,thank you for your samples.
i used your "simple sample" as a new project for testing account kit ,i clicked on "login via phone number" and filled my phone number,but it just showing "sending your code.. " dialog, and after some minutes said "we're sorry, some thing went wrong" , and just it. not working for me.
what's wrong?

**Comment by olgaikuznetsova** [comment]
Thanks for commenting. To debug this, please file a bug into our bug support system: https://developers.facebook.com/bugs/?tag_ids=1679169675664406

**Comment by HaDiSs277** [comment]
i found my problem , i never received code because i did not open vpn in my phone, 
can i have internal vpn in my app??
