### ISSUE TITLE
Couldn,t get country code/ISO

### ISSUE THREAD

**Issue by sohailniazai** [fbsamples/account-kit-samples-for-android#20]
After successful fetching of Access token , The phoneNumber does not have country code .

**Comment by saurabhdtu** [comment]
I am facing the same problem. The method
`account.getPhoneNumber().getCountryCodeIso()`
returns null.

**Comment by abeatte** [comment]
There are several ways in which the countryCodeIso is obtained (mainly from the phone number provided using a phone number parser). If a countryCodeIso is unable to be parsed then none will be returned. 

In testing, I am able to come up with countryCodeIsos. 
Do you notice that this only happens for specific phone numbers?
