### ISSUE TITLE
Could not read script copy_accountkit_sample.gradle' as it does not exist

### ISSUE THREAD

**Issue by TobinFrost** [fbsamples/account-kit-samples-for-android#26]
Error:(46, 0) Could not read script 'C:\internal\copy_accountkit_sample.gradle' as it does not exist.
<a href="openFile:C:\account-kit-samples-for-android\samples\AccountKitSample\build.gradle">Open File</a>

**Comment by abeatte** [comment]
How are you getting this error? That file should not be present in the repo so this may be fine.

**Comment by TobinFrost** [comment]
I got this by cloning the project from github

**Comment by abeatte** [comment]
Does it affect the repo or your ability to launch the samples?

**Comment by TobinFrost** [comment]
i can't just build the project with gradle because of the missing file.

**Comment by abeatte** [comment]
You can remove that line from the build.gradle and things should work. This change will be updated in the next SDK release. Thanks. :-)
