### ISSUE TITLE
Account kit recover account option

### ISSUE THREAD

**Issue by UsamaAmjad** [fbsamples/account-kit-samples-for-android#28]
We are integrating account kit into our app for login via phone. In case the user doesn't have the phone access later and not a FB user, after successful login we also ask user email address and save it in our DB for account recovery.
Now the question, is there any way in Account Kit to have recovery option like the user enters his recovery email, we send code on his email via account kit, and after verification we give him the **access to the profile which was registered with his phone number on account kit**? I can't find it in the documentation

**Comment by sgalzhrani9009** [comment]
كيف اسوي

**Comment by ct2mak** [comment]
There is currently no behavior that allows this at the moment. The user would need access to their phone number in order to get through Account Kit verification. You can do the necessary account merging on your end.
