### ISSUE TITLE
Error:Interface `com.google.android.gms.internal.auth.zze(classpath class)` used as super class of `com.google.android.gms.auth.api.signin.internal.zzs`.

### ISSUE THREAD

**Issue by oNguyenDucManh** [fbsamples/account-kit-samples-for-android#32]
I am using implementation  library:
implementation 'com.onesignal:OneSignal:3.10.1'
implementation 'com.google.android.gms:play-services-gcm:15.0.1'
implementation 'com.google.android.gms:play-services-vision:15.0.2'
implementation 'com.facebook.android:facebook-login:[4,5)'
implementation('com.facebook.android:account-kit-sdk:4.37.0') {
        exclude group: 'com.google.android.gms', module: 'play-services-auth-api-phone'
//        exclude group: 'com.google.android.gms', module: 'play-services-auth'
//        exclude group: 'com.google.android.gms', module: 'play-services-base'
    }
But when i run, IDE show messager error:
Error:Interface `com.google.android.gms.internal.auth.zze(classpath class)` used as super class of `com.google.android.gms.auth.api.signin.internal.zzs`.
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\admin\.gradle\caches\transforms-1\files-1.1\play-services-auth-15.0.1.aar\5da6c94f93418c3e19b4d8b1513a9fac\jars\classes.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
Error:com.android.tools.r8.CompilationFailedException: Compilation failed to complete
Error:com.android.tools.r8.utils.AbortException

**Comment by hasankucuk** [comment]
Did you find a solution to this?

**Comment by vikasbhagath** [comment]
has the problem is solved? i have same same error too?

**Comment by jffs** [comment]
ever solved?
