### ISSUE TITLE
New Google Policy Support? SMS Retriever instead of RECEIVE_SMS permission

### ISSUE THREAD

**Issue by rishabh876** [fbsamples/account-kit-samples-for-android#33]
As google has made special restriction on SMS and Call log permissions [more detail here](https://support.google.com/googleplay/android-developer/answer/9047303)
When will Account kit move to `SMS Retriever` and `HintRequest` so that we can remove these permissions. 
These permissions are anyways a big friction in Sign Up flow.

**Comment by khp** [comment]
Hi rishabh876, please see https://developers.facebook.com/blog/post/2019/01/08/new-google-play-policy-affects-account-kit-permission/ for current status of the SMS permission. We also have decided to not move forward with using the SMS Retriever API at this time.
