### ISSUE TITLE
Phone call verification cannot be received in China

### ISSUE THREAD

**Issue by gyxwudi** [fbsamples/account-kit-samples-for-android#35]
When I use voice call option in AccountKit Android SDK, I never receive a verification call,  but account kit shows "Sent". What can I do to make me receive the call ?

**Comment by hillbrad** [comment]
This is not an issue with the sample code. Availability of phone call verification varies by region and app. Direct support question about operational issues with Account Kit can be asked here: https://developers.facebook.com/support/
